version: '3'
services:
    app:
        build: docker
        ports:
            - 80:80
        volumes:
            - '.:/var/www/html/commercial-server'
        networks:
            - commercial
        depends_on:
            - mysql

    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
        ports:
            - 3306:3306
        networks:
            - commercial

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            PMA_PASSWORD: '${DB_PASSWORD}'
        restart: unless-stopped
        depends_on:
            - mysql
        networks:
            - commercial

networks:
    commercial:
        driver: bridge
